import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-pharma-wholesaler-chargeback-reconciliation",
  "engine": "recovery",
  "title": "Pharma Wholesaler Chargeback Reconciliation",
  "shortTitle": "Pharma Wholesaler Chargeback Reconciliation",
  "tagline": "Validate wholesaler chargebacks at contract-customer and NDC level and reconcile credits and deductions.",
  "industry": "Pharmaceutical Revenue Management",
  "buyer": "Pharmaceutical manufacturers",
  "uiPort": 4709,
  "apiPort": 5709,
  "accent": "#c2410c",
  "currency": "USD",
  "primaryOutcome": "Pharma Wholesaler Chargeback Reconciliation converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect customer contracts, identifiers, NDCs, wholesaler sales, chargeback claims, contract prices, eligibility dates, duplicates, credits, and deductions in one accountable workflow. Validate wholesaler chargebacks at contract-customer and NDC level and reconcile credits and deductions.",
  "calculation": {
    "actualKey": "receivedAmount",
    "expectedKey": "entitledAmount",
    "actualLabel": "Received or Recognized Amount",
    "expectedLabel": "Contract or Rule-Supported Entitlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Pharma Wholesaler Chargeback Reconciliation evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("contract-customer-registry","PWC01","Contract customer registry","Execute contract customer registry using customer contracts, identifiers, NDCs, wholesaler sales, chargeback claims, contract prices, eligibility dates, duplicates, credits, and deductions.","Produce a governed contract customer registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Wholesaler / Contract Customer","text","Wholesaler / Contract Customer · Standard Case"],["caseReference","Contract customer registry Reference","text","PWC01-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1415000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1712150],["domainDriver","Customer Class","select","GPO",["GPO","340B entity","Retail chain"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract customer registry case","Identifier hierarchy mapping case","NDC product registry case","Wholesaler sales ingestion case","Eligibility date validation case"]}),
feature("identifier-hierarchy-mapping","PWC02","Identifier hierarchy mapping","Execute identifier hierarchy mapping using customer contracts, identifiers, NDCs, wholesaler sales, chargeback claims, contract prices, eligibility dates, duplicates, credits, and deductions.","Produce a governed identifier hierarchy mapping decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Wholesaler / Contract Customer","text","Wholesaler / Contract Customer · Standard Case"],["caseReference","Identifier hierarchy mapping Reference","text","PWC02-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1415000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1712150],["domainDriver","Customer Class","select","GPO",["GPO","340B entity","Retail chain"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract customer registry case","Identifier hierarchy mapping case","NDC product registry case","Wholesaler sales ingestion case","Eligibility date validation case"]}),
feature("ndc-product-registry","PWC03","NDC product registry","Execute ndc product registry using customer contracts, identifiers, NDCs, wholesaler sales, chargeback claims, contract prices, eligibility dates, duplicates, credits, and deductions.","Produce a governed ndc product registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Wholesaler / Contract Customer","text","Wholesaler / Contract Customer · Standard Case"],["caseReference","NDC product registry Reference","text","PWC03-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1415000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1712150],["domainDriver","Customer Class","select","GPO",["GPO","340B entity","Retail chain"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract customer registry case","Identifier hierarchy mapping case","NDC product registry case","Wholesaler sales ingestion case","Eligibility date validation case"]}),
feature("wholesaler-sales-ingestion","PWC04","Wholesaler sales ingestion","Execute wholesaler sales ingestion using customer contracts, identifiers, NDCs, wholesaler sales, chargeback claims, contract prices, eligibility dates, duplicates, credits, and deductions.","Produce a governed wholesaler sales ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Wholesaler / Contract Customer","text","Wholesaler / Contract Customer · Standard Case"],["caseReference","Wholesaler sales ingestion Reference","text","PWC04-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1415000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1712150],["domainDriver","Customer Class","select","GPO",["GPO","340B entity","Retail chain"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract customer registry case","Identifier hierarchy mapping case","NDC product registry case","Wholesaler sales ingestion case","Eligibility date validation case"]}),
feature("eligibility-date-validation","PWC05","Eligibility date validation","Execute eligibility date validation using customer contracts, identifiers, NDCs, wholesaler sales, chargeback claims, contract prices, eligibility dates, duplicates, credits, and deductions.","Produce a governed eligibility date validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Wholesaler / Contract Customer","text","Wholesaler / Contract Customer · Standard Case"],["caseReference","Eligibility date validation Reference","text","PWC05-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1415000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1712150],["domainDriver","Customer Class","select","GPO",["GPO","340B entity","Retail chain"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract customer registry case","Identifier hierarchy mapping case","NDC product registry case","Wholesaler sales ingestion case","Eligibility date validation case"]}),
feature("contract-price-calculation","PWC06","Contract price calculation","Execute contract price calculation using customer contracts, identifiers, NDCs, wholesaler sales, chargeback claims, contract prices, eligibility dates, duplicates, credits, and deductions.","Produce a governed contract price calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Wholesaler / Contract Customer","text","Wholesaler / Contract Customer · Standard Case"],["caseReference","Contract price calculation Reference","text","PWC06-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1415000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1712150],["domainDriver","Customer Class","select","GPO",["GPO","340B entity","Retail chain"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract customer registry case","Identifier hierarchy mapping case","NDC product registry case","Wholesaler sales ingestion case","Eligibility date validation case"]}),
feature("wac-price-comparison","PWC07","WAC price comparison","Execute wac price comparison using customer contracts, identifiers, NDCs, wholesaler sales, chargeback claims, contract prices, eligibility dates, duplicates, credits, and deductions.","Produce a governed wac price comparison decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Wholesaler / Contract Customer","text","Wholesaler / Contract Customer · Standard Case"],["caseReference","WAC price comparison Reference","text","PWC07-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1415000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1712150],["domainDriver","Customer Class","select","GPO",["GPO","340B entity","Retail chain"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract customer registry case","Identifier hierarchy mapping case","NDC product registry case","Wholesaler sales ingestion case","Eligibility date validation case"]}),
feature("chargeback-amount-calculation","PWC08","Chargeback amount calculation","Execute chargeback amount calculation using customer contracts, identifiers, NDCs, wholesaler sales, chargeback claims, contract prices, eligibility dates, duplicates, credits, and deductions.","Produce a governed chargeback amount calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Wholesaler / Contract Customer","text","Wholesaler / Contract Customer · Standard Case"],["caseReference","Chargeback amount calculation Reference","text","PWC08-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1415000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1712150],["domainDriver","Customer Class","select","GPO",["GPO","340B entity","Retail chain"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract customer registry case","Identifier hierarchy mapping case","NDC product registry case","Wholesaler sales ingestion case","Eligibility date validation case"]}),
feature("duplicate-claim-detection","PWC09","Duplicate claim detection","Execute duplicate claim detection using customer contracts, identifiers, NDCs, wholesaler sales, chargeback claims, contract prices, eligibility dates, duplicates, credits, and deductions.","Produce a governed duplicate claim detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Wholesaler / Contract Customer","text","Wholesaler / Contract Customer · Standard Case"],["caseReference","Duplicate claim detection Reference","text","PWC09-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1415000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1712150],["domainDriver","Customer Class","select","GPO",["GPO","340B entity","Retail chain"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract customer registry case","Identifier hierarchy mapping case","NDC product registry case","Wholesaler sales ingestion case","Eligibility date validation case"]}),
feature("indirect-customer-validation","PWC10","Indirect customer validation","Execute indirect customer validation using customer contracts, identifiers, NDCs, wholesaler sales, chargeback claims, contract prices, eligibility dates, duplicates, credits, and deductions.","Produce a governed indirect customer validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Wholesaler / Contract Customer","text","Wholesaler / Contract Customer · Standard Case"],["caseReference","Indirect customer validation Reference","text","PWC10-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1415000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1712150],["domainDriver","Customer Class","select","GPO",["GPO","340B entity","Retail chain"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract customer registry case","Identifier hierarchy mapping case","NDC product registry case","Wholesaler sales ingestion case","Eligibility date validation case"]}),
feature("wholesaler-deduction-matching","PWC11","Wholesaler deduction matching","Execute wholesaler deduction matching using customer contracts, identifiers, NDCs, wholesaler sales, chargeback claims, contract prices, eligibility dates, duplicates, credits, and deductions.","Produce a governed wholesaler deduction matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Wholesaler / Contract Customer","text","Wholesaler / Contract Customer · Standard Case"],["caseReference","Wholesaler deduction matching Reference","text","PWC11-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1415000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1712150],["domainDriver","Customer Class","select","GPO",["GPO","340B entity","Retail chain"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract customer registry case","Identifier hierarchy mapping case","NDC product registry case","Wholesaler sales ingestion case","Eligibility date validation case"]}),
feature("rejection-remediation","PWC12","Rejection remediation","Execute rejection remediation using customer contracts, identifiers, NDCs, wholesaler sales, chargeback claims, contract prices, eligibility dates, duplicates, credits, and deductions.","Produce a governed rejection remediation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Wholesaler / Contract Customer","text","Wholesaler / Contract Customer · Standard Case"],["caseReference","Rejection remediation Reference","text","PWC12-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1415000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1712150],["domainDriver","Customer Class","select","GPO",["GPO","340B entity","Retail chain"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract customer registry case","Identifier hierarchy mapping case","NDC product registry case","Wholesaler sales ingestion case","Eligibility date validation case"]}),
feature("credit-memo-reconciliation","PWC13","Credit memo reconciliation","Execute credit memo reconciliation using customer contracts, identifiers, NDCs, wholesaler sales, chargeback claims, contract prices, eligibility dates, duplicates, credits, and deductions.","Produce a governed credit memo reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Wholesaler / Contract Customer","text","Wholesaler / Contract Customer · Standard Case"],["caseReference","Credit memo reconciliation Reference","text","PWC13-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1415000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1712150],["domainDriver","Customer Class","select","GPO",["GPO","340B entity","Retail chain"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract customer registry case","Identifier hierarchy mapping case","NDC product registry case","Wholesaler sales ingestion case","Eligibility date validation case"]}),
feature("accrual-true-up","PWC14","Accrual true-up","Execute accrual true-up using customer contracts, identifiers, NDCs, wholesaler sales, chargeback claims, contract prices, eligibility dates, duplicates, credits, and deductions.","Produce a governed accrual true-up decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Wholesaler / Contract Customer","text","Wholesaler / Contract Customer · Standard Case"],["caseReference","Accrual true-up Reference","text","PWC14-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1415000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1712150],["domainDriver","Customer Class","select","GPO",["GPO","340B entity","Retail chain"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract customer registry case","Identifier hierarchy mapping case","NDC product registry case","Wholesaler sales ingestion case","Eligibility date validation case"]}),
feature("wholesaler-product-analytics","PWC15","Wholesaler product analytics","Execute wholesaler product analytics using customer contracts, identifiers, NDCs, wholesaler sales, chargeback claims, contract prices, eligibility dates, duplicates, credits, and deductions.","Produce a governed wholesaler product analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Wholesaler / Contract Customer","text","Wholesaler / Contract Customer · Standard Case"],["caseReference","Wholesaler product analytics Reference","text","PWC15-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1415000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1712150],["domainDriver","Customer Class","select","GPO",["GPO","340B entity","Retail chain"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract customer registry case","Identifier hierarchy mapping case","NDC product registry case","Wholesaler sales ingestion case","Eligibility date validation case"]})
]);
